language: python
python:
  - "3.6"
# command to install dependencies
install:
  - "pip install numpy"
  - "pip install --install-option='--no-cython-compile' cython"
# command to run tests
script: python setup.py test
